# -*- coding: utf-8 -*-
"""lib/l10n/app_*.arb 생성기. 문자열을 고칠 땐 여기서 고치고 다시 실행한다.
   python tool/gen_arb.py
"""
import json, os

ko = {
 "@@locale":"ko",
 "appTitle":"나의 사주팔자",
 "onboardingTitle":"시작하기","settingsTitle":"설정",
 "onboardingHeadline":"태어난 날짜와 시간을 알려주세요",
 "onboardingBody":"생년월일시로 사주 여덟 글자를 풀어 성격·오행·오늘의 운세를 보여드려요.\n입력한 정보는 기기에만 저장됩니다.",
 "birthSection":"출생 정보","birthDate":"생년월일","birthDatePickerHelp":"생년월일 선택",
 "birthTime":"태어난 시각","birthTimePickerHelp":"태어난 시각",
 "hourUnknown":"태어난 시각을 몰라요","hourUnknownHint":"시주 없이 여섯 글자로 풀이해요",
 "solarCorrection":"진태양시 보정 (-30분)","solarCorrectionHint":"한국 출생이면 켜두세요. 전통 만세력 방식이에요",
 "notificationSection":"아침 알림","notificationToggleTitle":"매일 운세 알림",
 "notificationToggleSubtitle":"오늘의 일진과 운세를 알려드려요",
 "notificationTime":"알림 시간","notificationTimeHelp":"알림 시간",
 "save":"저장","goSeeSaju":"내 사주 보러 가기",
 "shareTooltip":"공유","settingsTooltip":"설정",
 "myChart":"나의 사주 원국","pillarHour":"시주","pillarDay":"일주","pillarMonth":"월주","pillarYear":"연주",
 "unknownHour":"모름",
 "dayMasterLabel":"나의 일간","dayMasterTitle":"{name} · {image}",
 "@dayMasterTitle":{"placeholders":{"name":{"type":"String"},"image":{"type":"String"}}},
 "elementBalance":"오행 분포","characterCount":"{n}글자 기준",
 "@characterCount":{"placeholders":{"n":{"type":"int"}}},
 "strongest":"강한 오행","weakest":"보완 오행",
 "todayFortune":"오늘의 운세","todayPillar":"오늘의 일진 {pillar}",
 "@todayPillar":{"placeholders":{"pillar":{"type":"String"}}},
 "fortuneIndex":"운세 지수","luckyNumber":"행운의 숫자","luckyColor":"행운의 색","luckyDirection":"행운의 방향",
 "seeDetail":"상세 해석 보기",
 "detailTitle":"상세 해석",
 "sectionPersonality":"일간으로 보는 성격","sectionElements":"오행 분석","sectionTenGods":"내 사주의 십신","sectionToday":"오늘의 운세 자세히",
 "godAt":"{pillar} {part}",
 "@godAt":{"placeholders":{"pillar":{"type":"String"},"part":{"type":"String"}}},
 "stemLabel":"천간","branchLabel":"지지",
 "detailFooter":"사주는 재미와 참고로 보는 콘텐츠예요. 오늘도 좋은 하루 보내세요 🌙",
 "shareTitle":"공유하기","shareAsImage":"이미지로 공유","shareAsText":"텍스트로 공유",
 "shareHint":"카카오톡, 인스타그램 스토리, 문자 등으로 보낼 수 있어요",
 "shareCardTitle":"나의 사주팔자","shareAppFooter":"나의 사주팔자 앱","shareImageCaption":"나의 사주팔자 ✨",
 "shareTextHeader":"📅 {date} 오늘의 운세 · 일진 {pillar}",
 "@shareTextHeader":{"placeholders":{"date":{"type":"String"},"pillar":{"type":"String"}}},
 "shareTextChart":"🔮 내 사주: {chart}",
 "@shareTextChart":{"placeholders":{"chart":{"type":"String"}}},
 "shareTextScore":"운세 지수 {score}점",
 "@shareTextScore":{"placeholders":{"score":{"type":"int"}}},
 "notifTitle":"🌙 오늘의 사주 운세가 도착했어요",
 "notifBody":"일진 {pillar} · 운세 지수 {score}점 · {text}",
 "@notifBody":{"placeholders":{"pillar":{"type":"String"},"score":{"type":"int"},"text":{"type":"String"}}},
 "notifChannelName":"오늘의 운세 알림","notifChannelDesc":"매일 아침 오늘의 사주 운세를 알려드립니다.",
 "zodiacLabel":"{animal}띠",
 "@zodiacLabel":{"placeholders":{"animal":{"type":"String"}}},
 "webShareUnsupported":"이미지 공유는 앱에서만 가능해요",
}

en = {
 "@@locale":"en","appTitle":"My Saju",
 "onboardingTitle":"Get started","settingsTitle":"Settings",
 "onboardingHeadline":"Tell us when you were born",
 "onboardingBody":"Your birth date and time become the eight characters of your Saju (Four Pillars): personality, five elements and today's fortune.\nYour data stays on this device.",
 "birthSection":"Birth info","birthDate":"Date of birth","birthDatePickerHelp":"Select date of birth",
 "birthTime":"Time of birth","birthTimePickerHelp":"Time of birth",
 "hourUnknown":"I don't know my birth time","hourUnknownHint":"Reads six characters without the hour pillar",
 "solarCorrection":"True solar time (-30 min)","solarCorrectionHint":"Turn on if born in Korea; traditional almanac method",
 "notificationSection":"Morning notification","notificationToggleTitle":"Daily fortune notification",
 "notificationToggleSubtitle":"Today's day pillar and fortune every morning",
 "notificationTime":"Notification time","notificationTimeHelp":"Notification time",
 "save":"Save","goSeeSaju":"See my Saju",
 "shareTooltip":"Share","settingsTooltip":"Settings",
 "myChart":"My Four Pillars","pillarHour":"Hour","pillarDay":"Day","pillarMonth":"Month","pillarYear":"Year",
 "unknownHour":"N/A",
 "dayMasterLabel":"My Day Master","dayMasterTitle":"{name} · {image}",
 "elementBalance":"Five elements","characterCount":"based on {n} characters",
 "strongest":"Strongest","weakest":"To strengthen",
 "todayFortune":"Today's fortune","todayPillar":"Today's pillar {pillar}",
 "fortuneIndex":"Fortune index","luckyNumber":"Lucky number","luckyColor":"Lucky color","luckyDirection":"Lucky direction",
 "seeDetail":"See full reading",
 "detailTitle":"Full reading",
 "sectionPersonality":"Personality by Day Master","sectionElements":"Element analysis","sectionTenGods":"Ten Gods in my chart","sectionToday":"Today in detail",
 "godAt":"{pillar} {part}",
 "stemLabel":"stem","branchLabel":"branch",
 "detailFooter":"Saju is for fun and reflection. Have a wonderful day 🌙",
 "shareTitle":"Share","shareAsImage":"Share as image","shareAsText":"Share as text",
 "shareHint":"Send via messaging apps, stories or SMS",
 "shareCardTitle":"My Saju","shareAppFooter":"My Saju app","shareImageCaption":"My Saju ✨",
 "shareTextHeader":"📅 {date} fortune · day pillar {pillar}",
 "shareTextChart":"🔮 My chart: {chart}",
 "shareTextScore":"Fortune index {score}",
 "notifTitle":"🌙 Your Saju fortune for today",
 "notifBody":"Day pillar {pillar} · index {score} · {text}",
 "notifChannelName":"Daily fortune","notifChannelDesc":"Your Saju fortune every morning.",
 "zodiacLabel":"Year of the {animal}",
 "webShareUnsupported":"Image sharing is available in the app only",
}

ja = {
 "@@locale":"ja","appTitle":"私の四柱推命",
 "onboardingTitle":"はじめる","settingsTitle":"設定",
 "onboardingHeadline":"生まれた日時を教えてください",
 "onboardingBody":"生年月日時から命式（八字）を出し、性格・五行・今日の運勢をお届けします。\n入力した情報は端末内にのみ保存されます。",
 "birthSection":"出生情報","birthDate":"生年月日","birthDatePickerHelp":"生年月日を選択",
 "birthTime":"生まれた時刻","birthTimePickerHelp":"生まれた時刻",
 "hourUnknown":"生まれた時刻がわからない","hourUnknownHint":"時柱なしの六文字で鑑定します",
 "solarCorrection":"真太陽時補正 (-30分)","solarCorrectionHint":"韓国生まれの方はオン。伝統的な万年暦の方式です",
 "notificationSection":"朝の通知","notificationToggleTitle":"毎日の運勢通知",
 "notificationToggleSubtitle":"今日の日柱と運勢をお知らせします",
 "notificationTime":"通知時刻","notificationTimeHelp":"通知時刻",
 "save":"保存","goSeeSaju":"私の命式を見る",
 "shareTooltip":"共有","settingsTooltip":"設定",
 "myChart":"私の命式","pillarHour":"時柱","pillarDay":"日柱","pillarMonth":"月柱","pillarYear":"年柱",
 "unknownHour":"不明",
 "dayMasterLabel":"私の日干","dayMasterTitle":"{name} · {image}",
 "elementBalance":"五行バランス","characterCount":"{n}文字基準",
 "strongest":"強い五行","weakest":"補いたい五行",
 "todayFortune":"今日の運勢","todayPillar":"今日の日柱 {pillar}",
 "fortuneIndex":"運勢指数","luckyNumber":"ラッキーナンバー","luckyColor":"ラッキーカラー","luckyDirection":"吉方位",
 "seeDetail":"詳しい鑑定を見る",
 "detailTitle":"詳しい鑑定",
 "sectionPersonality":"日干で見る性格","sectionElements":"五行分析","sectionTenGods":"命式の通変星","sectionToday":"今日の運勢の詳細",
 "godAt":"{pillar}{part}",
 "stemLabel":"天干","branchLabel":"地支",
 "detailFooter":"四柱推命は楽しみと参考のためのコンテンツです。今日も良い一日を 🌙",
 "shareTitle":"共有","shareAsImage":"画像で共有","shareAsText":"テキストで共有",
 "shareHint":"LINE、インスタのストーリー、SMS などで送れます",
 "shareCardTitle":"私の四柱推命","shareAppFooter":"私の四柱推命アプリ","shareImageCaption":"私の四柱推命 ✨",
 "shareTextHeader":"📅 {date} 今日の運勢 · 日柱 {pillar}",
 "shareTextChart":"🔮 私の命式: {chart}",
 "shareTextScore":"運勢指数 {score}点",
 "notifTitle":"🌙 今日の四柱推命が届きました",
 "notifBody":"日柱 {pillar} · 運勢指数 {score}点 · {text}",
 "notifChannelName":"今日の運勢通知","notifChannelDesc":"毎朝、今日の運勢をお知らせします。",
 "zodiacLabel":"{animal}年",
 "webShareUnsupported":"画像の共有はアプリでのみ可能です",
}

zh = {
 "@@locale":"zh","appTitle":"我的八字",
 "onboardingTitle":"开始","settingsTitle":"设置",
 "onboardingHeadline":"请告诉我们你的出生日期与时间",
 "onboardingBody":"根据出生年月日时排出八字命盘，为你解读性格、五行与今日运势。\n输入的信息仅保存在本机。",
 "birthSection":"出生信息","birthDate":"出生日期","birthDatePickerHelp":"选择出生日期",
 "birthTime":"出生时间","birthTimePickerHelp":"出生时间",
 "hourUnknown":"不知道出生时间","hourUnknownHint":"不排时柱，按六字解读",
 "solarCorrection":"真太阳时校正 (-30分钟)","solarCorrectionHint":"在韩国出生请开启，传统万年历方式",
 "notificationSection":"早间提醒","notificationToggleTitle":"每日运势提醒",
 "notificationToggleSubtitle":"每天早上告诉你今日日柱与运势",
 "notificationTime":"提醒时间","notificationTimeHelp":"提醒时间",
 "save":"保存","goSeeSaju":"查看我的八字",
 "shareTooltip":"分享","settingsTooltip":"设置",
 "myChart":"我的八字命盘","pillarHour":"时柱","pillarDay":"日柱","pillarMonth":"月柱","pillarYear":"年柱",
 "unknownHour":"未知",
 "dayMasterLabel":"我的日主","dayMasterTitle":"{name} · {image}",
 "elementBalance":"五行分布","characterCount":"按{n}字计算",
 "strongest":"最旺五行","weakest":"宜补五行",
 "todayFortune":"今日运势","todayPillar":"今日日柱 {pillar}",
 "fortuneIndex":"运势指数","luckyNumber":"幸运数字","luckyColor":"幸运颜色","luckyDirection":"幸运方位",
 "seeDetail":"查看详细解读",
 "detailTitle":"详细解读",
 "sectionPersonality":"日主看性格","sectionElements":"五行分析","sectionTenGods":"命盘中的十神","sectionToday":"今日运势详解",
 "godAt":"{pillar}{part}",
 "stemLabel":"天干","branchLabel":"地支",
 "detailFooter":"八字仅供娱乐与参考。祝你今天愉快 🌙",
 "shareTitle":"分享","shareAsImage":"以图片分享","shareAsText":"以文字分享",
 "shareHint":"可通过微信、短信等发送",
 "shareCardTitle":"我的八字","shareAppFooter":"我的八字 App","shareImageCaption":"我的八字 ✨",
 "shareTextHeader":"📅 {date} 今日运势 · 日柱 {pillar}",
 "shareTextChart":"🔮 我的八字: {chart}",
 "shareTextScore":"运势指数 {score}分",
 "notifTitle":"🌙 今日八字运势已送达",
 "notifBody":"日柱 {pillar} · 运势指数 {score}分 · {text}",
 "notifChannelName":"今日运势提醒","notifChannelDesc":"每天早上推送今日八字运势。",
 "zodiacLabel":"属{animal}",
 "webShareUnsupported":"图片分享仅在 App 内可用",
}

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, '..', 'lib', 'l10n')
keys = [k for k in ko if not k.startswith('@')]
for code, d in [('ko', ko), ('en', en), ('ja', ja), ('zh', zh)]:
    missing = [k for k in keys if k not in d]
    assert not missing, (code, missing)
    if code != 'ko':
        # 메타데이터(@key) 는 템플릿(ko)에만 있으면 된다.
        d = {k: v for k, v in d.items() if not k.startswith('@') or k == '@@locale'}
    with open(os.path.join(out, f'app_{code}.arb'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(json.dumps(d, ensure_ascii=False, indent=2) + '\n')
print('ok', len(keys), 'keys')
